config/routes.rb
Cupcake::Application.routes.draw do
  resources :signed_url, only: :index
  resources :stores do
    resources :ratings
  end
  resources :mastercakes do
    resources :ratings
  end
  resources :units
  resources :measures
  resources :ingredients

  resources :recipes do
    collection do
      get :cake
      get :filling
      get :frosting
    end
  end

  get "google_maps/index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/map', to: 'google_maps#index', via: 'get'
  match '/map', to: 'google_maps#index', via: 'post'
  root 'static_pages#home'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def google_map
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="bgpinkpaper">
	<div class="row">
		<div class="small-9 small-centered large-5 large-centered columns">
			<h1>Every Cupcake</h1>
		</div>
	</div>
	<div class="row">
		<div class="small-11 small-centered columns">
		<p>This project demonstrates Ruby on Rails development skills combined with a love for sweets!</p>
		</div>
	</div>
	<div class="row">
		<div class="small-5 small-centered columns">
			<%= image_tag image_url("bluechocolatelcf.png")%>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<% provide :title, 'Contact'%>
<h1> Contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
	Visit your favorite cupcake store for a fix.
</p>

app/views/static_pages/home.html.erb
<div class="bgpinkpaper">
	<div class="row">
		<div class="small-10 large-4 small-centered columns carousel">
			<!-- CAROUSEL -->
			<ul data-orbit >
				<li>
					<%= image_tag image_url("heart.png") %>
				</li>
				<li>
					<%= link_to (image_tag image_url("findstore.png")), map_path %>
				</li>				
				<li>
					<%= link_to (image_tag image_url("recipes.png")), mastercakes_path %>
				</li>
			</ul>
		</div>
	</div>
	<div class="row">
		<div class="small-5 large-2 small-centered columns">
			<%= link_to "Sign Up", signup_path, class:"button medium round signup-button" %>
		</div>
	</div>
</div>

app/views/static_pages/homelightbox.html.erb
<h1>Every Cupcake</h1>
<%= link_to 'Sign up now!', signup_path, class: "button small round"%>
<div class="row">
	<div class="large-9 small-9 columns">
		<div class="panel">
			<h4>Click on a photo to open the photo gallery</h4>
			<ul class="clearing-thumbs clearing-feature" data-clearing>
				<li class="clearing-featured-img">
					<%= image_tag image_url("heart.png"), class:'th' %>
				</li>
				<li>
					<%= image_tag image_url("findstore.png"), class:'th' %>
				</li>
				<li>
					<%= image_tag image_url("recipes.png"), height:150, class:'th' %>
				</li>
				<li>
					<%= image_tag "/assets/chocolatecc.jpeg", height:150, class:'th' %>
				</li>
			</ul>
		</div>
</div>