config/routes.rb
Cupcake::Application.routes.draw do
  resources :signed_url, only: :index
  resources :stores do
    resources :ratings
  end
  resources :mastercakes do
    resources :ratings
  end
  resources :units
  resources :measures
  resources :ingredients

  resources :recipes do
    collection do
      get :cake
      get :filling
      get :frosting
    end
  end

  get "google_maps/index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/map', to: 'google_maps#index', via: 'get'
  match '/map', to: 'google_maps#index', via: 'post'
  root 'static_pages#home'

  

end

app/models/mastercake.rb
class Mastercake < ActiveRecord::Base
	belongs_to :user
	has_many :recipes, :through => :cakecombos
	has_many :cakecombos
	has_many :ratings, as: :rateable
	has_many :reviews, as: :reviewable
	
	validates_presence_of :name, :source, :description
	validates :description, length: {maximum: 200}
	validates :name, length: {maximum: 40}
	# ADD AN IMAGE WITH PAPERCLIP

	# has_attached_file :image, styles: {
	# 	thumb: '190x150^'}, convert_options: {thumb: "-gravity center -extent 190x150"}
	
	# Add an image with Carrierwave
	mount_uploader :image, ImageUploader

	# PROCESS IMAGE AFTER SAVE FOR AMAZON S3 and CarrierWave DIRECT
	# after_save :enqueue_image

	# def image_name
	# 	File.basename(image.path || image.filename) if image
	# end

	# def enqueue_image
	# 	ImageWorker.perform_async(id, key) if key.present?
	# end
	# class ImageWorker
	# 	include Sidekiq::Worker

	# 	def perform(id, key)
	# 		mastercake = Mastercake.find(id)
	# 		mastercake.key = key
	# 		mastercake.remote_image_url = mastercake.image.direct_fog_url(with_path: true)
	# 		mastercake.save!
	# 		mastercake.update_column(:image_processed, true)
	# 	end
	# end
end

app/controllers/mastercakes_controller.rb
class MastercakesController < ApplicationController
  before_action :set_mastercake, only: [:show, :edit, :update, :destroy]

  def index
    @mastercakes = Mastercake.all
    # @uploader = Mastercake.new.image
    # @uploader.success_action_redirect = new_mastercake_url
  end

  def show
    @cake_recipes = @mastercake.recipes.where(cupcake_part: "cake")
    @filling_recipes = @mastercake.recipes.where(cupcake_part: "filling")
    @frosting_recipes = @mastercake.recipes.where(cupcake_part: "frosting")
    @rateable = @mastercake
    @ratings = @rateable.ratings
    @rating = Rating.new
  end

  def new
    @mastercake = Mastercake.new
    # @mastercake = Mastercake.new(key: params[:key])
  end

  def edit
  end

  def create
    # if params[:mastercake][:image_url]
    #   @image_url = params[:mastercake][:image_url]
    #   @current_cake_id = request.referer.split("/").last
    #   @mastercake= Mastercake.find(@current_cake_id)
    #   @mastercake.update_attribute(:image_url, @image_url)
    # else
      @mastercake = Mastercake.new(mastercake_params)
      @mastercake.update_attribute(:user_id, current_user.id)
    # end
    respond_to do |format|
      if @mastercake.save
        format.html { redirect_to @mastercake, notice: 'Cupcake was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mastercake }
      else
        format.html { render action: 'new' }
        format.json { render json: @mastercake.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def update
    respond_to do |format|
      if @mastercake.update(mastercake_params)
        format.html { redirect_to @mastercake, notice: 'Cupcake recipe was successfully updated.' }
        format.js
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.js 
        format.json { render json: @mastercake.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @mastercake.destroy
    respond_to do |format|
      format.html { redirect_to mastercakes_url }
      format.json { head :no_content }
    end
  end

  private
    def set_mastercake
      @mastercake = Mastercake.find(params[:id])
    end

    def mastercake_params
      params.require(:mastercake).permit(:name, :description, :source, :image_url, :image, :remote_image_url, :key,
                                         :recipe_ids, :user_id, :average_rating, :complete)
    end
end

app/helpers/mastercakes_helper.rb
module MastercakesHelper
end

app/views/mastercakes/_cake.html.erb
<div class="mastercakes">
    <% if object.image? %>
      <%= link_to (image_tag object.image.url(:thumb).to_s, :alt => object.name, 
                                        :title => object.description), object  %>
    <% else %>
      <%= link_to (image_tag image_url("placeholderimage.png"), :alt => "photo placeholder", :title => "Wanted Cupcake Photo"), object  %>
    <% end %>
  <div class="mastercake-name">
    <%= link_to object.name, object %>
  </div>
  <div class= "rating-bar">
    <%= render_stars(object.average_rating) %>
  </div>
  <div class="rating-number">
    <small><%= pluralize object.ratings.size, 'rating' %>  </small>
  
  <% if current_user && current_user.admin? || current_user == object.user %>
     <%= link_to 'edit', edit_mastercake_path(object) %> | <%= link_to 'remove', object, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  </div>
</div><!-- /end #mastercakes -->

app/views/mastercakes/_cake_photo.html.erb
<%= image_tag image_url(@mastercake.image) %>

app/views/mastercakes/_fields.html.erb
<%= f.label :name %><br>
<%= f.text_field :name %>

<%= f.label :description %><br>
<%= f.text_area :description %>

<%= f.label :source %><br>
<%= f.text_field :source %>

app/views/mastercakes/_form.html.erb
<%= form_for @mastercake do |f| %>
  <% if @mastercake.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mastercake.errors.count, "error") %> prohibited this mastercake from being saved:</h2>

      <ul>
      <% @mastercake.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= render 'fields', f: f %>
    <div class="row">
      <div class="large-6 small-10 columns">    
      <%= f.label :image, "Photo of Cupcake" %>
      <%= f.file_field :image %>
      </div>
    </div>
    <hr>
    <%#= f.hidden_field :key %>
    <%#= @mastercake.image_name %>
    
    <%= f.submit "Ready for Step 2", class: "medium round button"%>
<% end %>

app/views/mastercakes/_mastercake.html.erb
<% @mastercakes.each do |mastercake| %>
  <%= render 'mastercakes/cake', object: mastercake %>
<% end %>

app/views/mastercakes/_photo.html.erb
<%#= direct_upload_form_for @uploader do |f| %>
	<%#= f.file_field :image_url %>
	<%#= f.submit value: "update photo" %>

<%#= s3_uploader_form post: mastercakes_url(:js), as: "mastercake[image_url]" do %>
	<%#= file_field_tag :file, multiple: true %>
<%= image_tag image_url("placeholderimage.png"), :alt => "photo placeholder", :title => "Wanted Cupcake Photo" %>

app/views/mastercakes/_recipe.html.erb
<div>
  <div class="row">
    <div class="large-8 columns recipe-name">
      <div class="non-semantic-protector">
        <div class="ribbon">
          <span class="ribbon-content"><%= object.cupcake_part %>: <%= object.name %></span>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="large-8 columns recipe-format">
      <div class="row">
        <div class="large-6 columns">
          <h3>Ingredients:</h3>
            <ul class = "recipe">
              <% object.proportions.each do |item| %>
                <span class="ingredient">
                <li>
                  <span class="amount">
                	<% if item.unit %>
                  	<%= item.unit.name %>
                  <% end %>
                  <% if item.measure.name ==  "none (1 egg)" %>
                  <% else %>
                  <%= item.measure.name %>
                  <% end %>
                  </span>
                  <span class="name"><%= item.ingredient.name %></span>
                </li>
                </span>
              <% end %>
            </ul>
            <% if current_user == object.user %>
              <%= link_to 'Edit', edit_recipe_path(object) %>
            <% end %>
          </div>
          <div class="large-6 columns">
            <h3> Instructions: </h3>
            <ul class="bake-instructions">
              <% object.instructions.each do |instruction| %>
                <% if instruction.baketime %>
                <li>Bake for <span class="cooktime"><b><%= instruction.baketime %></b> minutes
                <span class="value-title" title=<%= "PT#{instruction.baketime}M"%>></span></span></li>
                <% end %>
                <% if instruction.baketemp %>
                <li>Oven Temperature: <%= instruction.baketemp%> °F</li>
                <% end %>
                <br>
                <li><span class="instructions"><%= markdown(instruction.content) %></span></li>
              <% end %>
              </ul>

            </div>
          </div>
      </div>

  </div>
</div>

app/views/mastercakes/create.js.erb
alert("got to the javascript create action");
<% if @mastercake.image_url.nil? %>
	alert("Failed to upload cupcake image: <%= j @mastercake.errors.full_messages.join(', ').html_safe %>");
<% else %>
	$("#image-frame").append("<div><%= j render 'cake_photo', object: @mastercake %></div>");
	$('.addphoto').hide();
	$('form.edit_mastercake').hide();
<% end %>

<% @image_url = "test" %>

app/views/mastercakes/edit.html.erb
<div class="row">
	<div class="small-11 small-centered large-6 large-centered columns">
		<h1><%= @mastercake.name %></h1>
	</div>
</div>
	<%= form_for @mastercake do |f| %>
		<div class="row">
			<div class="large-6 large-offset-3 columns">
				<%= render 'fields', f: f %>
				<%= f.submit "Save changes", class: "button round" %>
	<% end %>
			</div>
		</div>
		

<%= link_to 'Show', @mastercake %> |
<%= link_to 'Back', mastercakes_path %>

app/views/mastercakes/index.html.erb
<% provide :title, 'Recipes' %>
<div class="purplebg-paper">
<div class="color-me">
</div>
<div class="row">
  <div class="medium-9 medium-offset-1">
  <div class="small-11 large-9 columns">
    <div class="non-semantic-protector">
      <div class="ribbon">
        <span class="ribbon-content">Every Cupcake Recipe</span>
      </div>
    </div>
  </div>
  </div>
</div>
<div class="row">
  <% if current_user %>
    <div class="medium-9">
    <div class="large-5 large-offset-3 small-9 small-offset-3 columns">
    <%= link_to 'Create a Cupcake', new_mastercake_path, class:"add-cupcake" %>
    </div>
    </div>
  <% else %>
    <div class="medium-8">
    <div class="small-9 small-offset-3 large-6 large-offset-3 columns">
      <%= link_to 'Sign in to Add a Cupcake Recipe', signin_path, class:"add-cupcake" %>
    </div>
    </div>
  <% end %>
</div>
<div class="row">
  <div class="medium-10">
  <div class="large-9 columns">
    <ul class="small-block-grid-2 large-block-grid-4" >
      <% for mastercake in @mastercakes %>
      <li>
        <%= render 'cake', object: mastercake %>
      </li>
      <% end %>
    </ul>
  </div>
  </div>
</div>

<%#= direct_upload_form_for @uploader do |f| %>
<%#= f.file_field :image %>
<%#= f.submit "Upload Image" %>
<% #end %>

app/views/mastercakes/new.html.erb
<%= provide :title, "New Cupcake Recipe" %>
	<div class="row">
		<div class="large-7 large-offset-1 small-10 small-offset-1 columns">
    <div class="non-semantic-protector">
      <div class="ribbon">
        <span class="ribbon-content">Step 1: The Basics</span>
      </div>
    </div>
  </div>
	</div>
<div class="row">
	<div class="large-7 large-offset-1 small-10 small-offset-1 columns">
    <fieldset class="thebasics">
			<%= render 'form' %>
		</fieldset>
		<%= link_to "Cupcake Recipes", mastercakes_path %>
	</div>
</div>

app/views/mastercakes/show.html.erb
<%= provide :title, @mastercake.name %>
<div class="hrecipe">
	<div class="row"><!-- CAKE TITLE -->
		<div class="large-8 small-12 columns recipe-name">
			<div class="non-semantic-protector">
				<div class="ribbon">
					<span class="item fn ribbon-content"><%= @mastercake.name %></span>
				</div>
			</div>
		</div>
		<div class="large-3 large-offset-1 small-12 columns">
			<br>
			<br>
			<% if current_user && !@mastercake.ratings.pluck(:user_id).include?(current_user.id) && @mastercake.user_id != current_user.id %>
			<a href="#" data-reveal-id="reviewModal" class="cake-review-button">Review Recipe</a>
			<% else %>
				<% if current_user.nil? %>
					<%= link_to "Sign in to Review", signin_path %>
				<% end %>
			<% end %>
		</div>
	</div><!-- Recipe Title Ribbon TOP ROW LARGE -->
		<div class="row">
			<div class="small-6 small-centered columns">
				
			</div>
		</div><!-- End modal rating link -->
		<div class="row">
			<div class="large-3 columns">
				<div class="mastercakes">
				    <% if @mastercake.image? %>
				    	<div class="mastercake">
				      <%= image_tag @mastercake.image.url(:thumb), :alt => @mastercake.name, 
				                                        :title => @mastercake.description, class: "photo" %>
				      </div>
				    <% else %>
								<%= image_tag image_url("placeholderimage.png"), :alt => "photo placeholder", :title => "Wanted Cupcake Photo",
								class: "photo" %>
				    <% end %>
				  <br>
				  <span class="review hreview-aggregate">
				  <div class= "rating-bar rating">
				    <%= render_stars(@mastercake.average_rating) %>
				  </div>
				  <div class="rating-number rating">
				    <small><span class="average"><%= pluralize @mastercake.average_rating, 'star ' %>based on</span><span class="count"> <%= pluralize @mastercake.ratings.size, 'review' %></span></small>
				  </div>
				  </span>
				</div><!-- /end #mastercakes -->
			</div><!-- /end of mastercake image view polaroid -->
			<div class="large-5 columns">
				<div class="cake-info"> 
						<span class="summary"><%= markdown(@mastercake.description) %></span>
						<p>
						 <b>Source: </b><%= @mastercake.source %>
						</p>
						<div class="row">
							<div class= "large-1 columns ">
								<% if @mastercake.user == current_user %>
									<%= link_to 'Edit', edit_mastercake_path(@mastercake) %>
								<% end %>
							</div>
						</div>
				</div>
			</div>
			<div class="large-4 columns">
				<h3 class="review-title">REVIEWS</h3>
				<% for rating in @mastercake.ratings %>
					<fieldset class="review-block">
							<div class="rating-bar">
							<%= render_stars(rating.star) %>
							</div>
							<div class="review-text">
							<%= rating.review %>
							</div>
							<div class="review-author">
							Cupcake Aficionado: <%= rating.user.name if rating.user %>
							</div>
					</fieldset>
				<% end %>
			</div>
		</div><!-- end of mastercake info section -->
		<% if @cake_recipes.count >= 1 %>
			<% @cake_recipes.each do |cake| %>
				<%= render "recipe", object: cake %>
			<% end %>
		<% end %>
		<% if @filling_recipes.count >= 1 %>
					<% @filling_recipes.each do |filling| %>
						<%= render "recipe", object: filling %>
					<% end %>
		<% end %>
		<% if @frosting_recipes.count >= 1 %>
					<% @frosting_recipes.each do |frosting| %>
						<%= render "recipe", object: frosting %>
					<% end %>
		<% end %>
</div><!-- end of Microformat recipe hrecipe markup -->
<% if !current_user.nil? and @mastercake.user_id == current_user.id %>
	<div>
		<div class="recipe-choices">
			<h3>Click Image to Build Recipe</h3>
		</div>
		<ul class="ch-grid">
			<li>
				<div class="ch-item ch-img-1">
					<div class="ch-info-wrap">
						<div class="ch-info">
							<div class="ch-info-front ch-img-1"></div>
							<div class="ch-info-back">
								<p><%= link_to "CAKE", cake_recipes_path(mastercake_id: @mastercake.id) %></p>
							</div>
						</div>
					</div>
				</div>
			</li>
			<li>
				<div class="ch-item ch-img-2">
					<div class="ch-info-wrap">
						<div class="ch-info">
							<div class="ch-info-front ch-img-2"></div>
							<div class="ch-info-back">
								<p><%= link_to "FILLING", filling_recipes_path(mastercake_id: @mastercake.id) %></p>
							</div>
						</div>
					</div>
				</div>
			</li>
			<li>
				<div class="ch-item ch-img-3">
					<div class="ch-info-wrap">
						<div class="ch-info">
							<div class="ch-info-front ch-img-3"></div>
							<div class="ch-info-back">
								<p><%= link_to "FROSTING", frosting_recipes_path(mastercake_id: @mastercake.id) %></p>
							</div>
						</div>
					</div>
				</div>
			</li>
		</ul>
	</div>
<% end %>
		<div class="row">
			<div class="large-4 columns">
			<%= form_for @mastercake do |f| %>
		    <%#= f.label :recipe_ids, "Using Existing Cake Recipe" %>
		    <%#= f.collection_select :recipe_ids, Recipe.where(:cupcake_part => "cake"), :id, :name %>
		  </div>
		  <div class="large-4 columns">
		    <%#= f.label :recipe_ids, "Select a Filling Recipe" %>
		    <%#= f.collection_select :recipe_ids, Recipe.where(:cupcake_part => "filling"), :id, :name %>
		  </div>
		  <div class="large-4 columns">
		    <%#= f.label :recipe_ids, "Select a Frosting Recipe" %>
		    <%#= f.collection_select :recipe_ids, Recipe.where(:cupcake_part => "frosting"), :id, :name %>
		  </div>
		</div>
		    <%#= f.submit "Add Existing Recipe", class: "medium button round" %>
		  <% end %>

				<%= link_to 'View All Cupcakes', mastercakes_path %>
	</div>

	<div class="reveal-modal-bg" style="display: none"></div>
	<div id="reviewModal" class="reveal-modal">
		<h1>Review <%= @mastercake.name %></h1>
		<%= render "ratings/form" %>
	  <a class="close-reveal-modal">&#215;</a>
	</div>

app/views/mastercakes/update.js.erb
<% if @mastercake.image.nil? %>
	alert("Failed to upload cupcake image: <%= j @mastercake.errors.full_messages.join(', ').html_safe %>");
<% else %>
	$("#image-frame").append("<div><%= j render 'cake_photo', object: @mastercake %></div>");
	$('.addphoto').hide();
	$('form.edit_mastercake').hide();
<% end %>